import './globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import FirebaseManager from './FirebaseManager';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="overflow-x-hidden bg-[#020617]">
        <FirebaseManager />
        {children}
      </body>
    </html>
  )
}
